//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Activity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Activity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.App.Resources.Texts.Activity", typeof(Activity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DetailActivity_Delete {
            get {
                return ResourceManager.GetString("DetailActivity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DetailActivity_Description {
            get {
                return ResourceManager.GetString("DetailActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string DetailActivity_Duration {
            get {
                return ResourceManager.GetString("DetailActivity_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DetailActivity_Edit {
            get {
                return ResourceManager.GetString("DetailActivity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string DetailActivity_End {
            get {
                return ResourceManager.GetString("DetailActivity_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string DetailActivity_ProjectName {
            get {
                return ResourceManager.GetString("DetailActivity_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string DetailActivity_Start {
            get {
                return ResourceManager.GetString("DetailActivity_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity detail.
        /// </summary>
        internal static string DetailActivity_Title {
            get {
                return ResourceManager.GetString("DetailActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DetailActivity_Type {
            get {
                return ResourceManager.GetString("DetailActivity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string DetailActivity_UserName {
            get {
                return ResourceManager.GetString("DetailActivity_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EditActivity_End {
            get {
                return ResourceManager.GetString("EditActivity_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string EditActivity_Project {
            get {
                return ResourceManager.GetString("EditActivity_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditActivity_Save {
            get {
                return ResourceManager.GetString("EditActivity_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string EditActivity_Start {
            get {
                return ResourceManager.GetString("EditActivity_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or edit activity.
        /// </summary>
        internal static string EditActivity_Title {
            get {
                return ResourceManager.GetString("EditActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string EditActivity_Type {
            get {
                return ResourceManager.GetString("EditActivity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        internal static string FilterActivity_30Days {
            get {
                return ResourceManager.GetString("FilterActivity_30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        internal static string FilterActivity_7Days {
            get {
                return ResourceManager.GetString("FilterActivity_7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        internal static string FilterActivity_ApplyFilters {
            get {
                return ResourceManager.GetString("FilterActivity_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        internal static string FilterActivity_ClearFilters {
            get {
                return ResourceManager.GetString("FilterActivity_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string FilterActivity_EndDate {
            get {
                return ResourceManager.GetString("FilterActivity_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterActivity_Filter {
            get {
                return ResourceManager.GetString("FilterActivity_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string FilterActivity_LastMonth {
            get {
                return ResourceManager.GetString("FilterActivity_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string FilterActivity_LastYear {
            get {
                return ResourceManager.GetString("FilterActivity_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string FilterActivity_StartDate {
            get {
                return ResourceManager.GetString("FilterActivity_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Day.
        /// </summary>
        internal static string FilterActivity_ThisDay {
            get {
                return ResourceManager.GetString("FilterActivity_ThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string FilterActivity_ThisMonth {
            get {
                return ResourceManager.GetString("FilterActivity_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string FilterActivity_ThisYear {
            get {
                return ResourceManager.GetString("FilterActivity_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add activity.
        /// </summary>
        internal static string ListActivity_Add {
            get {
                return ResourceManager.GetString("ListActivity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ListActivity_Title {
            get {
                return ResourceManager.GetString("ListActivity_Title", resourceCulture);
            }
        }
    }
}
