//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.App.Resources.Texts {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypesTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypesTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TimeTracker.App.Resources.Texts.TypesTexts", typeof(TypesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        internal static string accounting {
            get {
                return ResourceManager.GetString("accounting", resourceCulture);
            }
        }
        
        internal static string backend {
            get {
                return ResourceManager.GetString("backend", resourceCulture);
            }
        }
        
        internal static string design {
            get {
                return ResourceManager.GetString("design", resourceCulture);
            }
        }
        
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        internal static string frontend {
            get {
                return ResourceManager.GetString("frontend", resourceCulture);
            }
        }
        
        internal static string hiring {
            get {
                return ResourceManager.GetString("hiring", resourceCulture);
            }
        }
        
        internal static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        internal static string kick_off {
            get {
                return ResourceManager.GetString("kick_off", resourceCulture);
            }
        }
        
        internal static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        internal static string marketing {
            get {
                return ResourceManager.GetString("marketing", resourceCulture);
            }
        }
        
        internal static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        internal static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        internal static string ux_ui {
            get {
                return ResourceManager.GetString("ux_ui", resourceCulture);
            }
        }
        
        internal static string others {
            get {
                return ResourceManager.GetString("others", resourceCulture);
            }
        }
    }
}
